# Generated by Django 6.1.1 on 2026-09-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('source', models.CharField(choices=[('kobo', 'KoboToolbox (API)'), ('upload', 'Fichier importé (CSV/Excel/SPSS)')], default='upload', max_length=10)),
                ('kobo_base_url', models.CharField(blank=True, default='https://kf.kobotoolbox.org', help_text='ex: https://kf.kobotoolbox.org ou https://eu.kobotoolbox.org', max_length=200, verbose_name='URL de base Kobo')),
                ('kobo_api_token', models.CharField(blank=True, max_length=200, verbose_name='Token API Kobo')),
                ('kobo_asset_uid', models.CharField(blank=True, max_length=100, verbose_name='UID du formulaire (asset)')),
                ('dedup_key_column', models.CharField(blank=True, max_length=200, verbose_name='Colonne clé de dé-doublonnage (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Résultats et analyses', max_length=200)),
                ('blocks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_uuid', models.CharField(blank=True, db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'kobo_uuid'], name='core_submis_project_368ad4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VariableMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('var_type', models.CharField(choices=[('numerique', 'Numérique'), ('categorielle', 'Catégorielle'), ('likert', 'Likert / échelle'), ('date', 'Date'), ('texte', 'Texte libre')], default='categorielle', max_length=20)),
                ('recoding_map', models.JSONField(blank=True, null=True, verbose_name='Table de recodage (ex: {"1":"Homme","2":"Femme"})')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Utilisable comme filtre du tableau de bord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
